public with sharing class Constants {
    public static String PRODUCT_INFO_ERROR_NO_PRODUCTS_FOR_CONTACT = System.Label.Product_Info_No_Products_for_Contact;
    public static String PRODUCT_INFO_ERROR_CONTACT_FIELDS_MISSING = System.Label.Product_Info_Contact_fields_are_missing;
    public static String PRODUCT_INFO_ERROR_CONTACT_MISSING = System.Label.Product_Info_No_Contact_for_Current_Case;

    public static String CONTACT_REST_ERROR_NO_UUIDS_PROVIDED = System.Label.Contact_Info_Error_No_UUIDs_Provided;
    public static String CONTACT_REST_ERROR_NO_CONTACTS_FOUND = System.Label.Contact_Info_Error_No_Contacts_Found;

    public static String PRODUCT_INFO_FIELD_SET_NAME = 'Product_Information';

    public static String CARD_SERVICE_API_NAME = 'Card_Service__c';

    public static String CONTACT_FIELD_API_NAME_HOME_COUNTRY = 'Home_Country__c';
    public static String CONTACT_FIELD_API_NAME_PRODUCT = 'Product__c';

    public static String HOME_COUNTRY_DE = 'DE';
    public static String HOME_COUNTRY_FR = 'FR';

    public static String URL_PARAM_UUIDS = 'uuids';
}