public with sharing class Constants {
    public static String PRODUCT_INFO_NO_PRODUCTS_FOR_CONTACT = System.Label.Product_Info_No_Products_for_Contact;
    public static String PRODUCT_INFO_CONTACT_FIELDS_MISSING = System.Label.Product_Info_Contact_fields_are_missing;
    public static String PRODUCT_INFO_CONTACT_MISSING = System.Label.Product_Info_No_Contact_for_Current_Case;

    public static String PRODUCT_INFO_FIELD_SET_NAME = 'Product_Information';

    public static String CARD_SERVICE_API_NAME = 'Card_Service__c';
}